Battle Fantasia
BlazBlue Calamity Trigger
BlazBlue Continuum Shift
Chaos Breaker
Goketsuji Ichizoku - Matsuri Senzo Kuyou
King of Fighters 98, The - The Ultimate Match
King of Fighters XII, The
King of Fighters XIII, The
KOF - Maximum Impact Regulation A
Samurai Shodown - Edge of Destiny
Street Fighter IV
Super Street Fighter IV Arcade Edition
Super Street Fighter IV Arcade Edition (Version 2012)
